document.getElementById("o1").innerHTML="<span onclick='#' style='position:relative;top:150px;left:0px;background-color:transparent;color:yellow;font-size:60px;'id='myleft'>&#10218;</span>&ensp;&ensp;&ensp;&ensp;&ensp;<span onclick='wh2();' style='position:relative;top:150px;left:74%;background-color:transparent;color:yellow;font-size:60px;'id='myright'id='myright'>&#10219</span><iframe src='https://www.youtube.com/embed/FjbzOjA5ZNw?rel=0' width='100%' height='30%'allowfullscreen scrolling='no' allow='accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share;'></iframe>";
function wh1(){
document.getElementById("o1").innerHTML="<span onclick='#' style='position:relative;top:150px;left:0px;background-color:transparent;color:yellow;font-size:60px;'id='myleft'>&#10218</span>&ensp;&ensp;&ensp;&ensp;&ensp;<span onclick='wh2();' style='position:relative;top:150px;left:74%;background-color:transparent;color:yellow;font-size:60px;'id='myright'>&#10219</span><iframe src='https://www.youtube.com/embed/FjbzOjA5ZNw?rel=0' width='100%' height='30%'allowfullscreen scrolling='no' allow='accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share;'></iframe>";
}
function wh2(){
document.getElementById("o1").innerHTML="<span onclick='wh1()' style='position:relative;top:150px;left:0px;background-color:transparent;color:yellow;font-size:60px;'id='myleft'>&#10218</span>&ensp;&ensp;&ensp;&ensp;&ensp;<span onclick='wh3();' style='position:relative;top:150px;left:74%;background-color:transparent;color:yellow;font-size:60px;'id='myright'>&#10219</span><iframe src='https://www.youtube.com/embed/ptJoXh0EY3Q?rel=0' width='100%' height='30%'allowfullscreen scrolling='no' allow='accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share;'></iframe>";
}
function wh3(){
document.getElementById("o1").innerHTML="<span onclick='wh2();' style='position:relative;top:150px;left:0px;background-color:transparent;color:yellow;font-size:60px;'id='myleft'>&#10218</span>&ensp;&ensp;&ensp;&ensp;&ensp;<span onclick='wh4();' style='position:relative;top:150px;left:74%;background-color:transparent;color:yellow;font-size:60px;'id='myright'>&#10219</span><iframe src='https://www.youtube.com/embed/TK8TkDG056I?rel=0' width='100%' height='30%'allowfullscreen scrolling='no' allow='accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share;'></iframe>";
}
document.getElementById("o").innerHTML="<span onclick='#' style='position:relative;top:150px;left:0px;background-color:transparent;color:yellow;font-size:60px;'id='myleft'>&#10218</span>&ensp;&ensp;&ensp;&ensp;&ensp;<span onclick='kalinga2();' style='position:relative;top:150px;left:74%;background-color:transparent;color:yellow;font-size:60px;'id='myright'>&#10219</span><embed src='/kalinga2.jpg' width='100%'></embed>";
function kalinga1(){
document.getElementById("o").innerHTML="<span onclick='#' style='position:relative;top:150px;left:0px;background-color:transparent;color:yellow;font-size:60px;'id='myleft'>&#10218</span>&ensp;&ensp;&ensp;&ensp;&ensp;<span onclick='kalinga2();' style='position:relative;top:150px;left:74%;background-color:transparent;color:yellow;font-size:60px;'id='myright'>&#10219</span><embed src='/kalinga2.jpg' width='100%'></embed>";
}
function kalinga2(){
document.getElementById("o").innerHTML="<span onclick='kalinga1();' style='position:relative;top:150px;left:0px;background-color:transparent;color:yellow;font-size:60px;'id='myleft'>&#10218</span>&ensp;&ensp;&ensp;&ensp;&ensp;<span onclick='#' style='position:relative;top:150px;left:74%;background-color:transparent;color:yellow;font-size:60px;'id='myright'>&#10219</span><embed src='/kalinga1.jpg' width='100%'></embed>";
}
